server:
  port: 18736

spring:
  application:
    name: movie-recommend
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    elasticsearch:
      cluster-nodes: 192.168.207.11:59300
      cluster-name: daas5
      clientPingTimeout: 5s
      clientTransportSniff: falseas
      clientIgnoreClusterName: true
      repositories:
        enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.73:13306/movie_recommend?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type:  com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    max_idle:  5
    min_idle: 1
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validataion-query: select 1

  thymeleaf:
    cache: false

logging:
  config: classpath:logback.xml

#线程配置
thread:
  corePoolSize: 10
  maxPoolSize: 10
  queneCapacity: 10
  keepAliveSeconds: 60000


